CREATE TABLE dbo.ZIP_CODE (
    CODE BIGINT NOT NULL,
    CONSTRAINT PK_ZIPCODE_INDEX PRIMARY KEY(CODE)
);

CREATE TABLE dbo.SUBJECT (
    ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SUBJECT_INDEX PRIMARY KEY(ID)
);

CREATE TABLE dbo.TUTOR (
    ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SUBJECT BIGINT NOT NULL,
    RATE REAL NOT NULL, 
    ZIP BIGINT NOT NULL,
    CONSTRAINT PK_TUTOR_INDEX PRIMARY KEY(ID),
    CONSTRAINT FK_TUTOR_SUBJECT FOREIGN KEY(SUBJECT) REFERENCES dbo.SUBJECT(ID),
    CONSTRAINT FK_TUTOR_ZIP FOREIGN KEY(ZIP) REFERENCES dbo.ZIP_CODE(CODE)
);

CREATE TABLE dbo.STUDENT (
    ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SUBJECT BIGINT NOT NULL,
    ZIP BIGINT NOT NULL,
    CONSTRAINT PK_STUDENT_INDEX PRIMARY KEY(ID),
    CONSTRAINT FK_STUDENT_SUBJECT FOREIGN KEY(SUBJECT) REFERENCES dbo.SUBJECT(ID),
    CONSTRAINT FK_STUDENT_ZIP FOREIGN KEY(ZIP) REFERENCES dbo.ZIP_CODE(CODE)
);

CREATE TABLE dbo.CLASSROOM (
    ID BIGINT NOT NULL,
    TUTOR BIGINT NOT NULL,
    STUDENT BIGINT NOT NULL,
    TIMESTAMP DATETIME NOT NULL,
    CONSTRAINT PK_CLASSROOM_INDEX PRIMARY KEY(ID),
    CONSTRAINT FK_CLASSROOM_STUDENT FOREIGN KEY(STUDENT) REFERENCES dbo.STUDENT(ID),
    CONSTRAINT FK_CLASSROOM_TUTOR FOREIGN KEY(TUTOR) REFERENCES dbo.TUTOR(ID)
);