INSERT INTO ZIP_CODE VALUES(33065);
INSERT INTO ZIP_CODE VALUES(33076);
INSERT INTO ZIP_CODE VALUES(33427);
INSERT INTO ZIP_CODE VALUES(33431);

INSERT INTO SUBJECT VALUES(1, 'Algebra');
INSERT INTO SUBJECT VALUES(2, 'Physics 1');
INSERT INTO SUBJECT VALUES(3, 'Physics 2');
INSERT INTO SUBJECT VALUES(4, 'Chemistry');

INSERT INTO TUTOR VALUES(1, 'John Cena', 1, 15.0, 33065);